sonar.projectKey=sme-autosservico-backend
sonar.projectName=SME Autosservico Backend
sonar.projectVersion=1.0

sonar.sources=apps,config
sonar.tests=apps/core/tests,config/tests,apps/sigpae/tests

sonar.language=py
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
  **/migrations/**,**/migrations/*.py,**/venv/**,**/.venv/**,**/env/**,\
  **/__pycache__/**,**/*.pyc,**/templates/**,**/templates/*.html,\
  **/static/**,**/media/**,**/locale/**,**/htmlcov/**,**/docs/**,\
  **/requirements/**,**/utility/**,**/scripts/**,**/testes/**,manage.py,\
  **/manage.py,config/wsgi.py,config/settings.py,**/conftest.py,\
  **/apps.py,**/admin.py,**/__init__.py

sonar.test.exclusions=**/tests/**,**/test_*.py,**/conftest.py,**/factories.py,**/*_test.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.cpd.exclusions=**/migrations/**,**/tests/**
sonar.cpd.python.minimumLines=10
